name: Build PyRunner APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Gradle
      run: |
        wget -q https://services.gradle.org/distributions/gradle-7.4.2-bin.zip
        unzip -q gradle-7.4.2-bin.zip
        echo "GRADLE_HOME=$PWD/gradle-7.4.2" >> $GITHUB_ENV
        echo "$GRADLE_HOME/bin" >> $GITHUB_PATH

    - name: Generate Gradle Wrapper
      run: |
        if [ ! -f "gradlew" ]; then
          echo "Generating Gradle Wrapper..."
          gradle wrapper --gradle-version 7.4.2
        else
          echo "Gradle Wrapper already exists."
        fi

    - name: Commit Gradle Wrapper Files (if generated)
      run: |
        if [ -f "gradlew" ] && [ -n "$(git status --porcelain)" ]; then
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add gradlew gradlew.bat gradle/
          git commit -m "Add Gradle Wrapper files generated by GitHub Actions"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        sdk-version: '33'
        accept-licenses: 'yes'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
