name: Build PyRunner APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Update to latest version

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3  # Update to latest version
      with:
        sdk-version: '33'
        accept-licenses: 'yes'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4  # Update to v4 (or latest)
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
